version: '3'
services:
  api:
    build: .
    ports:
      - "4445:4445"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://Silva:nrLCrBfGIet3fvOU@mongodb:27017
      - PORT=4445

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Silva
      - MONGO_INITDB_ROOT_PASSWORD=nrLCrBfGIet3fvOU
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=Silva
      - ME_CONFIG_MONGODB_ADMINPASSWORD=nrLCrBfGIet3fvOU
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo-data:
